generatorName: rust
outputDir: samples/client/others/rust/reqwest/oneOf-aliases
library: reqwest
inputSpec: modules/openapi-generator/src/test/resources/3_0/rust/issue_17869_oneOf_aliases.yaml
templateDir: modules/openapi-generator/src/main/resources/rust
additionalProperties:
  supportAsync: false
  packageName: oneof-reqwest-oneOf-aliases
